package com.summer.section1.group7.eco_resort.Piya.controller;

import com.summer.section1.group7.eco_resort.User;
import com.summer.section1.group7.eco_resort.Piya.model.AppendableObjectOutputStream;
import com.summer.section1.group7.eco_resort.Piya.model.Room;
import com.summer.section1.group7.eco_resort.Piya.model.RoomReservation;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.stage.Stage;

import java.io.*;

public class RoomReservationController {

    @FXML
    private DatePicker checkInDP;

    @FXML
    private DatePicker checkOutDP;

    @FXML
    private ComboBox<Integer> guestCountCB;

    @FXML
    private ComboBox<String> roomTypeCB;

    @FXML
    private Label messageLabel;


    private Room selectedRoom;

    private User currentUser;


    public void setCurrentUser(User user) {
        this.currentUser = user;
    }


    @FXML
    public void initialize() {

        roomTypeCB.getItems().addAll(
                "Single",
                "Deluxe",
                "Suite",
                "Family"
        );

        guestCountCB.getItems().addAll(
                1,2,3,4,5,6,7,8,9,10
        );
    }


    @FXML
    public void checkRoomAvailableButtonOA(ActionEvent actionEvent) {

        messageLabel.setText("");
        selectedRoom = null;


        if(roomTypeCB.getValue() == null){

            messageLabel.setText(
                    "Please select room type."
            );

            return;
        }


        File file = new File("Room.bin");


        if(!file.exists()){

            messageLabel.setText(
                    "No room data found."
            );

            return;
        }


        try(ObjectInputStream ois =
                    new ObjectInputStream(
                            new FileInputStream(file)
                    )){


            while(true){

                try{

                    Room room =
                            (Room) ois.readObject();


                    if(room.getRoomType()
                            .equals(roomTypeCB.getValue())
                            &&
                            room.getAvailability()
                                    .equalsIgnoreCase("Available")){


                        selectedRoom = room;
                        break;

                    }


                }
                catch(EOFException e){

                    break;

                }

            }


            if(selectedRoom == null){

                messageLabel.setText(
                        "No room available."
                );

            }
            else{

                messageLabel.setText(
                        "Room available."
                );

            }


        }
        catch(Exception e){

            e.printStackTrace();

        }

    }



    @FXML
    public void bookRoomButtonOA(ActionEvent actionEvent) {


        messageLabel.setText("");


        if(checkInDP.getValue() == null
                ||
                checkOutDP.getValue() == null
                ||
                roomTypeCB.getValue() == null){


            messageLabel.setText(
                    "Please fill all fields."
            );

            return;

        }



        if(!checkOutDP.getValue()
                .isAfter(checkInDP.getValue())){


            messageLabel.setText(
                    "Invalid booking dates."
            );

            return;

        }



        if(selectedRoom == null){

            messageLabel.setText(
                    "Please check room availability first."
            );

            return;

        }



        if(currentUser == null){

            messageLabel.setText(
                    "User not logged in."
            );

            return;

        }



        // Reservation ID will be generated by receptionist later
        RoomReservation reservation =
                new RoomReservation(
                        null,
                        checkInDP.getValue(),
                        checkOutDP.getValue(),
                        "Pending",
                        currentUser,
                        selectedRoom
                );



        File file =
                new File("RoomReservation.bin");



        try{


            FileOutputStream fos;
            ObjectOutputStream oos;



            if(file.exists()){


                fos = new FileOutputStream(
                        file,
                        true
                );


                oos =
                        new AppendableObjectOutputStream(
                                fos
                        );


            }
            else{


                fos =
                        new FileOutputStream(file);


                oos =
                        new ObjectOutputStream(
                                fos
                        );

            }



            oos.writeObject(reservation);

            oos.close();



            messageLabel.setText(
                    "Room booking request sent."
            );


        }
        catch(Exception e){

            e.printStackTrace();

            messageLabel.setText(
                    "Failed to save reservation."
            );

        }

    }



    @FXML
    public void backButtonOA(ActionEvent actionEvent) {


        try{


            FXMLLoader loader =
                    new FXMLLoader(
                            getClass().getResource(
                                    "/com/summer/section1/group7/eco_resort/Piya/GuestDashboard.fxml"
                            )
                    );


            Scene scene =
                    new Scene(
                            loader.load()
                    );



            Stage stage =
                    (Stage)((Node)actionEvent.getSource())
                            .getScene()
                            .getWindow();



            stage.setScene(scene);

            stage.show();


        }
        catch(Exception e){

            e.printStackTrace();

        }

    }

}